[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android]
ar = "/home/harry/android-ndk-r27d/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
linker = "/home/harry/android-ndk-r27d/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang"
rustflags = [
    "-C", "link-arg=--sysroot=/home/harry/android-ndk-r27d/toolchains/llvm/prebuilt/linux-x86_64/sysroot",
    "-C", "link-arg=-fuse-ld=lld",
]
